# Generated by Django 5.2.13 on 2026-04-19 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='faculty',
            field=models.CharField(blank=True, choices=[('muhendislik', 'Mühendislik Fakültesi'), ('fen_edebiyat', 'Fen-Edebiyat Fakültesi'), ('iktisadi_idari', 'İktisadi ve İdari Bilimler Fakültesi'), ('egitim', 'Eğitim Fakültesi'), ('saglik', 'Sağlık Bilimleri Fakültesi'), ('tip', 'Tıp Fakültesi'), ('ziraat', 'Ziraat Fakültesi'), ('ilahiyat', 'İlahiyat Fakültesi'), ('guzel_sanatlar', 'Güzel Sanatlar Fakültesi'), ('hukuk', 'Hukuk Fakültesi')], max_length=50, null=True),
        ),
    ]
