# Generated by Django 5.2.13 on 2026-04-19 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_loginactivity'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='loginactivity',
            options={'ordering': ['-login_at']},
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='is_approved',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='status',
            field=models.CharField(choices=[('pending', 'Onay Bekliyor'), ('approved', 'Onaylandı'), ('rejected', 'Reddedildi')], default='pending', max_length=20),
        ),
    ]
