# Generated by Django 5.2.13 on 2026-04-28 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_loginactivity_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='password_reset_version',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
