# Generated by Django 5.2.13 on 2026-05-08 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_userprofile_password_reset_version"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="faculty",
            field=models.CharField(
                blank=True, max_length=180, null=True, verbose_name="Fakülte / Mevki"
            ),
        ),
    ]
