# Generated by Django 5.2.13 on 2026-05-03 17:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("streams", "0003_camera_faculty"),
    ]

    operations = [
        migrations.CreateModel(
            name="SpeedCameraConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("enabled", models.BooleanField(default=False)),
                ("speed_limit_kmh", models.FloatField(default=50.0)),
                ("tolerance_kmh", models.FloatField(default=10.0)),
                (
                    "calibration_path",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Örnek: HizTespiti/calibration/out_calibration/cam_001_calibration.json",
                        max_length=500,
                    ),
                ),
                ("roi_enabled", models.BooleanField(default=False)),
                ("roi_polygon", models.JSONField(blank=True, default=list)),
                ("save_snapshot", models.BooleanField(default=True)),
                ("save_clip", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "camera",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="speed_config",
                        to="streams.camera",
                    ),
                ),
            ],
            options={
                "verbose_name": "Hız Tespiti Kamera Ayarı",
                "verbose_name_plural": "Hız Tespiti Kamera Ayarları",
            },
        ),
    ]
