# Generated by Django 5.2.13 on 2026-05-08 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FacultyLocation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=150, unique=True, verbose_name="Fakülte / Mevki Adı"
                    ),
                ),
                (
                    "code",
                    models.SlugField(
                        blank=True, max_length=180, unique=True, verbose_name="Kod"
                    ),
                ),
                (
                    "location_type",
                    models.CharField(
                        choices=[("faculty", "Fakülte"), ("location", "Mevki")],
                        default="faculty",
                        max_length=20,
                        verbose_name="Tür",
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="Açıklama")),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Aktif mi?"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Oluşturulma Tarihi"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Güncellenme Tarihi"
                    ),
                ),
            ],
            options={
                "verbose_name": "Fakülte / Mevki",
                "verbose_name_plural": "Fakülte / Mevkiler",
                "ordering": ["location_type", "name"],
            },
        ),
    ]
