# Generated by Django 5.2.13 on 2026-05-08 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("adminx", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="facultylocation",
            options={
                "ordering": ["name"],
                "verbose_name": "Fakülte / Mevki",
                "verbose_name_plural": "Fakülte / Mevkiler",
            },
        ),
        migrations.RemoveField(
            model_name="facultylocation",
            name="location_type",
        ),
    ]
