# Generated by Django 5.2.13 on 2026-04-17 23:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('streams', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CameraAccess',
        ),
    ]
