# Generated by Django 5.2.13 on 2026-05-03 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("streams", "0003_camera_faculty"),
    ]

    operations = [
        migrations.AddField(
            model_name="camera",
            name="use_fight_detection",
            field=models.BooleanField(
                default=True,
                help_text="Bu kamera kavga tespiti modülünde kullanılsın.",
                verbose_name="Kavga Tespiti",
            ),
        ),
        migrations.AddField(
            model_name="camera",
            name="use_speed_detection",
            field=models.BooleanField(
                default=False,
                help_text="Bu kamera hız tespiti modülünde kullanılsın.",
                verbose_name="Hız Tespiti",
            ),
        ),
    ]
