# Generated by Django 5.2.13 on 2026-05-08 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("streams", "0003_camera_faculty"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="camera",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Kamera",
                "verbose_name_plural": "Kameralar",
            },
        ),
        migrations.AlterField(
            model_name="camera",
            name="camera_id",
            field=models.CharField(
                max_length=100, unique=True, verbose_name="Camera ID"
            ),
        ),
        migrations.AlterField(
            model_name="camera",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="Oluşturulma Tarihi"
            ),
        ),
        migrations.AlterField(
            model_name="camera",
            name="description",
            field=models.TextField(blank=True, verbose_name="Açıklama"),
        ),
        migrations.AlterField(
            model_name="camera",
            name="faculty",
            field=models.CharField(
                blank=True, max_length=180, null=True, verbose_name="Fakülte / Mevki"
            ),
        ),
        migrations.AlterField(
            model_name="camera",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Aktif mi?"),
        ),
        migrations.AlterField(
            model_name="camera",
            name="name",
            field=models.CharField(max_length=120, verbose_name="Kamera Adı"),
        ),
        migrations.AlterField(
            model_name="camera",
            name="source",
            field=models.CharField(max_length=500, verbose_name="Kaynak"),
        ),
        migrations.AlterField(
            model_name="camera",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, verbose_name="Güncellenme Tarihi"
            ),
        ),
    ]
