# Generated by Django 5.2.13 on 2026-05-08 06:16

import streams.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("streams", "0004_alter_camera_options_alter_camera_camera_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="camera",
            name="uploaded_video",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=streams.models.camera_video_upload_to,
                verbose_name="Yüklenen Video",
            ),
        ),
        migrations.AlterField(
            model_name="camera",
            name="source",
            field=models.CharField(
                blank=True,
                help_text="RTSP/HTTP/IP kamera adresi, cihaz index'i veya yüklenen video dosyasının path'i.",
                max_length=500,
                null=True,
                verbose_name="Kaynak",
            ),
        ),
    ]
