# Generated by Django 5.2.13 on 2026-05-13 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("streams", "0004_camera_use_fight_detection_and_more"),
        ("streams", "0005_camera_uploaded_video_alter_camera_source"),
    ]

    operations = []
